id: P006709
initial_creation_type: ocr
created_at: 24/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG5872
  title: བསམ་ཡས་རྩོད་པ།
  author: ''
  volumes:
    0bfee802400a427d89ed7d5d216100e9:
      image_group_id: I1KG5891
      title: ''
      volume_number: 1
      total_pages: 489
      base_file: v001.txt
